-- Supabase SQL schema for Automated Student Pickup Verification System

-- 1. students table
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  first_name text not null,
  middle_name text,
  last_name text not null,
  grade_level text,
  section text,
  created_at timestamp with time zone default timezone('utc', now()),
  updated_at timestamp with time zone default timezone('utc', now())
);

alter table public.students add column if not exists first_name text;
alter table public.students add column if not exists middle_name text;
alter table public.students add column if not exists last_name text;
alter table public.students add column if not exists grade_level text;
alter table public.students add column if not exists section text;

alter table public.students drop column if exists name;
alter table public.students drop column if exists class;
alter table public.students drop column if exists qr_code;

-- 2. pickups table
create table if not exists public.pickups (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  parent_id bigint,
  picked_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- 3. parents table (optional if you want parent profiles)
create table if not exists public.parents (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  first_name text not null,
  middle_name text,
  last_name text not null,
  relationship text not null,
  mobile_number text not null,
  email text,
  created_at timestamp with time zone default timezone('utc', now()),
  updated_at timestamp with time zone default timezone('utc', now())
);

alter table public.parents add column if not exists auth_user_id uuid;
alter table public.parents drop constraint if exists parents_auth_user_id_fkey;
alter table public.parents
  add constraint parents_auth_user_id_fkey
  foreign key (auth_user_id) references auth.users(id) on delete cascade;
create unique index if not exists idx_parents_auth_user_id
  on public.parents (auth_user_id)
  where auth_user_id is not null;

alter table public.pickups add column if not exists parent_id bigint;
alter table public.pickups drop constraint if exists pickups_parent_id_fkey;
alter table public.pickups
  add constraint pickups_parent_id_fkey
  foreign key (parent_id) references public.parents(id) on delete set null;

alter table public.parents add column if not exists email text;
create unique index if not exists idx_parents_email_unique
  on public.parents (lower(email))
  where email is not null;

-- 4. staff table for staff access / approvals
create table if not exists public.staff (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  middle_name text,
  last_name text,
  email text not null unique,
  phone_number text,
  photo_url text,
  is_approved boolean default false,
  created_at timestamptz default now()
);

alter table public.staff alter column email drop not null;

create index if not exists idx_staff_email
  on public.staff (email);

-- Optional RLS setup for the staff table
alter table public.staff enable row level security;

create policy "staff can view own record"
on public.staff
for select
using (auth.uid() = id);

create policy "service role can manage staff"
on public.staff
for all
using (true)
with check (true);

-- 7. admins table for system administrators
create table if not exists public.admins (
  id uuid primary key default gen_random_uuid(),
  first_name text,
  middle_name text,
  last_name text,
  email text not null unique,
  phone_number text unique,
  password_hash text not null,
  is_active boolean default true
);

create index if not exists idx_admins_email
  on public.admins (email);
create unique index if not exists idx_admins_phone_number_unique
  on public.admins (phone_number)
  where phone_number is not null;

alter table public.admins add column if not exists phone_number text;

-- 8. Add role and status fields to existing tables for better management
alter table public.parents add column if not exists is_active boolean default true;
alter table public.parents add column if not exists student_id bigint references public.students(id) on delete cascade;

alter table public.staff add column if not exists role text default 'staff'; -- staff, supervisor
alter table public.staff add column if not exists is_active boolean default true;
alter table public.staff alter column is_approved set default false;

-- RLS for admins table
alter table public.admins enable row level security;

create policy "admins can manage own record"
on public.admins
for select
using (auth.uid() = id);

create policy "service role can manage admins"
on public.admins
for all
using (true)
with check (true);
